// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQg90nkiOJQSNwhp40-dUAtj4CJx9TR0',
    appId: '1:639002445242:web:83d42e53a704d01f16c983',
    messagingSenderId: '639002445242',
    projectId: 'finance-43467',
    authDomain: 'finance-43467.firebaseapp.com',
    storageBucket: 'finance-43467.appspot.com',
    measurementId: 'G-D6JC3PET3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi1vXw5GhnErK8aXR4bP9EUki9YjWnS8c',
    appId: '1:639002445242:android:f7ea520b86d77c7c16c983',
    messagingSenderId: '639002445242',
    projectId: 'finance-43467',
    storageBucket: 'finance-43467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC096fKZ88OPgW-7S_V6RGqY9FV2-NQbvw',
    appId: '1:639002445242:ios:2cbc2fb88cf2d30416c983',
    messagingSenderId: '639002445242',
    projectId: 'finance-43467',
    storageBucket: 'finance-43467.appspot.com',
    iosClientId: '639002445242-mrpj5rklcr044pldpa95jph4g8m5frn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC096fKZ88OPgW-7S_V6RGqY9FV2-NQbvw',
    appId: '1:639002445242:ios:2cbc2fb88cf2d30416c983',
    messagingSenderId: '639002445242',
    projectId: 'finance-43467',
    storageBucket: 'finance-43467.appspot.com',
    iosClientId: '639002445242-mrpj5rklcr044pldpa95jph4g8m5frn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance',
  );
}
